'use client';

import Link from 'next/link';
import Header from '../components/Header';
import Footer from '../components/Footer';

// This page explains how StoryNest handles user data and privacy
export default function PrivacyPolicyPage() {
    return (
        <div className="min-h-screen font-poppins bg-story-lavender flex flex-col">
            <Header />

            <main className="flex-grow pt-28 pb-16 px-4 sm:px-6 lg:px-8 relative overflow-hidden">
                {/* Decorative background blobs to keep the theme magical */}
                <div className="absolute top-20 left-0 w-96 h-96 bg-story-purple rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob"></div>
                <div className="absolute top-20 right-0 w-96 h-96 bg-story-gold rounded-full mix-blend-multiply filter blur-3xl opacity-20 animate-blob animation-delay-2000"></div>

                <div className="container mx-auto relative z-10 max-w-4xl">
                    {/* Page Title */}
                    <div className="text-center mb-12 animate-fade-in-up">
                        <h1 className="text-4xl md:text-5xl font-bold font-fredoka text-story-purple mb-4">
                            Privacy Policy
                        </h1>
                        <p className="text-lg text-gray-600">
                            Last updated: April 29, 2026
                        </p>
                    </div>

                    {/* The main box containing all the privacy details */}
                    <div className="bg-white/80 backdrop-blur-sm rounded-3xl p-8 md:p-12 shadow-xl border border-purple-100 animate-fade-in-up">
                        <div className="prose prose-lg max-w-none">

                            {/* Section 1: Introduction */}
                            <section className="mb-8">
                                <h2 className="text-2xl font-bold font-fredoka text-gray-900 mb-4">1. Introduction</h2>
                                <p className="text-gray-700 leading-relaxed mb-4">
                                    At StoryNest, we are committed to protecting your privacy and providing a safe and secure experience for all our users, especially children. This Privacy Policy explains how we collect, use, and safeguard your personal information when you use our AI-powered story creation platform.
                                </p>
                            </section>

                            {/* Section 2: Information We Collect */}
                            <section className="mb-8">
                                <h2 className="text-2xl font-bold font-fredoka text-gray-900 mb-4">2. Information We Collect</h2>
                                <p className="text-gray-700 leading-relaxed mb-4">
                                    We collect information that you provide directly to us when you create an account, use our service, or communicate with us. This may include:
                                </p>
                                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                                    <li>Account information (name, email address, password)</li>
                                    <li>Profile information (child's name, age, interests for story personalization)</li>
                                    <li>Content you create (story prompts, preferences, generated stories)</li>
                                    <li>Communication data (if you contact our support team)</li>
                                </ul>
                            </section>

                            {/* Section 3: How We Use Your Information */}
                            <section className="mb-8">
                                <h2 className="text-2xl font-bold font-fredoka text-gray-900 mb-4">3. How We Use Your Information</h2>
                                <p className="text-gray-700 leading-relaxed mb-4">
                                    We use the information we collect to:
                                </p>
                                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                                    <li>Provide, maintain, and improve StoryNest services</li>
                                    <li>Personalize the stories generated by our AI</li>
                                    <li>Communicate with you about your account and updates</li>
                                    <li>Ensure the safety and security of our platform</li>
                                    <li>Analyze usage patterns to enhance user experience</li>
                                </ul>
                            </section>

                            {/* Section 4: Children's Privacy */}
                            <section className="mb-8">
                                <h2 className="text-2xl font-bold font-fredoka text-gray-900 mb-4">4. Children's Privacy</h2>
                                <p className="text-gray-700 leading-relaxed mb-4">
                                    StoryNest is designed for family use. We take extra precautions to protect children's privacy:
                                </p>
                                <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
                                    <li>We do not collect more personal information from children than is reasonably necessary to provide the service.</li>
                                    <li>Parents/guardians have the right to review, delete, or refuse further collection of their child's information.</li>
                                    <li>We do not sell children's personal data to third parties.</li>
                                </ul>
                            </section>

                            {/* Section 5: Data Security */}
                            <section className="mb-8">
                                <h2 className="text-2xl font-bold font-fredoka text-gray-900 mb-4">5. Data Security</h2>
                                <p className="text-gray-700 leading-relaxed mb-4">
                                    We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, loss, or alteration. However, no method of transmission over the Internet or electronic storage is 100% secure.
                                </p>
                            </section>

                            {/* Section 6: AI Content and Privacy */}
                            <section className="mb-8">
                                <h2 className="text-2xl font-bold font-fredoka text-gray-900 mb-4">6. AI Content and Privacy</h2>
                                <p className="text-gray-700 leading-relaxed mb-4">
                                    The prompts and information you provide to generate stories are processed by our AI models. While we use this data to generate your content, we strive to ensure that sensitive personal information is not shared with third-party AI providers in a way that identifies you.
                                </p>
                            </section>

                            {/* Section 7: Your Rights */}
                            <section className="mb-8">
                                <h2 className="text-2xl font-bold font-fredoka text-gray-900 mb-4">7. Your Rights</h2>
                                <p className="text-gray-700 leading-relaxed mb-4">
                                    Depending on your location, you may have certain rights regarding your personal information, including the right to access, correct, or delete your data. You can manage most of your information through your account settings.
                                </p>
                            </section>

                            {/* Section 8: Changes to This Policy */}
                            <section className="mb-8">
                                <h2 className="text-2xl font-bold font-fredoka text-gray-900 mb-4">8. Changes to This Policy</h2>
                                <p className="text-gray-700 leading-relaxed mb-4">
                                    We may update this Privacy Policy from time to time. We will notify you of any material changes by posting the new policy on this page and updating the "Last updated" date.
                                </p>
                            </section>

                            {/* Section 9: Contact Us */}
                            <section className="mb-8">
                                <h2 className="text-2xl font-bold font-fredoka text-gray-900 mb-4">9. Contact Us</h2>
                                <p className="text-gray-700 leading-relaxed mb-4">
                                    If you have any questions or concerns about this Privacy Policy or our data practices, please contact us via{' '}
                                    <Link href="/contact-us" className="text-story-purple font-semibold hover:underline">
                                        our contact page
                                    </Link>.
                                </p>
                            </section>

                        </div>
                    </div>
                </div>
            </main>

            <Footer />
        </div>
    );
}
